services:
  database:
    image: postgres:16-alpine
    container_name: gamenest-database
    environment:
      POSTGRES_DB: gamenest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/seed/001_initial_data.sql:/docker-entrypoint-initdb.d/02-seed.sql

  backend:
    build:
      context: ./backend
    container_name: gamenest-backend
    depends_on:
      - database
    environment:
      PORT: 3000
      NODE_ENV: development
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: gamenest
      DB_USER: postgres
      DB_PASSWORD: postgres
      IGDB_CLIENT_ID: ${IGDB_CLIENT_ID}
      IGDB_CLIENT_SECRET: ${IGDB_CLIENT_SECRET}
    ports:
      - "3000:3000"
  frontend:
    build:
      context: ./frontend
    container_name: gamenest-frontend
    depends_on:
      - backend
    ports:
      - "8082:80"

volumes:
  postgres_data: